### ISSUE TITLE
Prefixing commands with nvm.sh sucks

### ISSUE THREAD

**Issue by Almad** [apiaryio/docker-base-images#10]
As far as I know, `NODE_PATH` is almost the only thing nvm changes [citation needed].

Wouldn't it be better to set it explicitly via `ENV` so when inheriting from the base image, I could use `npm` directly?

**Comment by abtris** [comment]
I think https://github.com/apiaryio/docker-base-images/pull/15/files fixed this problem.

**Comment by Almad** [comment]
Yes.
