### ISSUE TITLE
Cant Start Backend Server

### ISSUE THREAD

**Issue by chandanadesilva** [apiaryio/docker-base-images#149]
How do I start the dredd backend server using this docker image ?

**Comment by abtris** [comment]
Dredd was moved into separate repository https://github.com/apiaryio/dredd-docker

**Comment by honzajavorek** [comment]
@chandanadesilva I think the solution would be to use [Docker Compose](https://docs.docker.com/compose/overview/), which starts your app, starts Dredd testing with correct IP address of your app, and then [finishes when Dredd is done](https://stackoverflow.com/a/41841714/325365). Would that work for you?
